[project]
name = "expert-jb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.5.1",
    "pandas>=2.2.3",
    "pyyaml>=6.0.2",
    "torch>=2.7.0",
    "trl>=0.15.2",
    "unsloth>=2025.4.7",
]
